name: bst_finance
description: "Aplikasi Keuangan CV. Berkarya Satu Tujuan"
publish_to: 'none'
version: 1.2.6+3
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  url_launcher: ^6.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.5.0
  # --- FIREBASE ---
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  # --- STATE MANAGEMENT ---
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^9.2.0

  # --- UI & UTILS ---
  google_fonts: ^6.1.0
  intl: ^0.20.2
  uuid: ^4.2.2
  flutter_svg: ^2.0.9
  fl_chart: ^1.1.1

  # --- PAYROLL ---
  pdf: ^3.11.3
  printing: ^5.9.3
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  rxdart: ^0.28.0
  excel: ^4.0.0
  open_filex: ^4.4.0
  firebase_messaging: ^16.1.0

flutter_launcher_icons:
  image_path: "lib/assets/logo_perusahaan.png" # Path ke file ikon Anda
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - shorebird.yaml